robot:
  type: woan_teleop_follower
  id: follower_arm
  port: /dev/ttyACM2
  robot_model: damiao_left
  version: v3.2
  woan_description_path: /home/woan/woan_description
  slcan_type: damiao
  use_velocity: true
  enable_gripper: true
  cameras:
    wrist1:
      type: opencv
      index_or_path: "/dev/v4l/by-path/pci-0000:80:14.0-usb-0:6.1.2:1.0-video-index0"
      width: 640
      height: 480
      fps: 30
    wrist2:
      type: opencv
      index_or_path: "/dev/v4l/by-path/pci-0000:80:14.0-usb-0:6.1.2:1.2-video-index0"
      width: 640
      height: 480
      fps: 30

teleop:
  type: woan_teleop_leader
  id: leader_arm
  port: /dev/ttyACM0
  robot_model: damiao_left
  version: v3.2
  woan_description_path: /home/woan/woan_description
  slcan_type: damiao
  use_velocity: true
  enable_gripper_joystick: true

dataset:
  repo_id: test/teleop_record_test
  root: /home/woan/lerobot/tmp/datasets/test/teleop_record_test
  single_task: "Follow the leader to pick the cube"
  num_episodes: 8
  fps: 30
  episode_time_s: 45
  reset_time_s: 30
  video: true
  push_to_hub: false
  

display_data: true
display_ip: 127.0.0.1
display_port: 9876